### PR TITLE
Gaurav8604

### LINKED ISSUE #285: Add new folder Leetcode
Add new folder for leetcode problems 
and add problems of 2Sum, 3Sum and 4Sum problems in java
Please add the hactoberfest tag.

### PR DESCRIPTION
**Pull request by Gaurav8604**
# Description

Addition of a new folder in src/test/java folder named LeetCode

Also changed the filename src/test/java/Newton_School/Baldev:The_Destoryer to src/test/java/Newton_School/Baldev_The_Destoryer to allow windows users to fork as windows cannot special characters in file or folder name.

Fixes #285 

## Type of change

Please select options that are relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration A**:
* Input:
* Expected Output:
* Explanation:

**Test Configuration B**:
* Input:
* Expected Output:
* Explanation:

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, could you kick off the discussion by explaining why you chose the solution you did, what alternatives you considered, etc...

### CODE REVIEW

**Comment by Gaurav8604** [comment]
@Vedeesh6 I think now it should work. I have named each class a unique name.

**Comment by Vedeesh6** [comment]
Done

**Comment by Vedeesh6** [comment]
@Gaurav8604 Do you have a **Holopin** id? If yes or you would like to create one then send your mailid here. We are giving an exclusive contribution badge for our repository this month.

**Comment by Gaurav8604** [comment]
Sure!
Here it is 
holopin.io/@gaurav8604

@Vedeesh6

**Comment by Vedeesh6** [comment]
> Sure! Here it is holopin.io/@Gaurav8604
> 
> @Vedeesh6



> @Gaurav8604 Do you have a **Holopin** id? If yes or you would like to create one then send your mailid here. We are giving an exclusive contribution badge for our repository this month.

Great but I wanted your mail id.

**Comment by Vedeesh6** [comment]
Also, you can call out your friends to contribute here. This is a one-month chance to gain the exclusive badge.
Thanks

**Comment by Gaurav8604** [comment]
Sure! @Vedeesh6 ans thanks once again.
Appreciate your repository.

**Comment by Vedeesh6** [comment]
> Sure! @Vedeesh6 ans thanks once again. Appreciate your repository.

You're welcome!

> Great but I wanted your mail id.

You missed this

**Pull request merged**
